[build]
  base = "reclaim-app"
  command = "next build"
  publish = "reclaim-app/.next"

# Use the official Next.js runtime/plugin on Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Node version for build environment
[build.environment]
  NODE_VERSION = "20"
