-- Add more affirmations (20 per category)

INSERT INTO affirmations (category, text, is_default) VALUES
-- Morning affirmations (6 more to make 20 total)
('morning', 'I trust my instincts and inner wisdom today', true),
('morning', 'I am not responsible for managing her emotions', true),
('morning', 'Today I choose my mental health over keeping the peace', true),
('morning', 'I deserve relationships built on mutual respect', true),
('morning', 'Her chaos does not define my day', true),
('morning', 'I am learning to love myself through this healing journey', true),

-- Boundary affirmations (10 more to make 20 total)
('boundary', 'I do not need to justify my boundaries', true),
('boundary', 'My time and energy are precious resources', true),
('boundary', 'I can love someone and still protect myself from them', true),
('boundary', 'Saying no to her is saying yes to myself', true),
('boundary', 'I am not obligated to respond to every demand', true),
('boundary', 'My boundaries are acts of self-love', true),
('boundary', 'I choose peace over people-pleasing', true),
('boundary', 'I will not set myself on fire to keep others warm', true),
('boundary', 'Her urgency is not my emergency', true),
('boundary', 'I have the right to change my mind about my boundaries', true),

-- Self-compassion affirmations (6 more to make 20 total)
('self-compassion', 'I am learning and growing every day', true),
('self-compassion', 'My feelings are valid and important', true),
('self-compassion', 'I forgive myself for not knowing what I didn''t know', true),
('self-compassion', 'I am enough, exactly as I am', true),
('self-compassion', 'I treat myself with the same kindness I show others', true),
('self-compassion', 'My past does not determine my future', true),

-- Strength affirmations (20 new)
('strength', 'I have survived 100% of my difficult days so far', true),
('strength', 'I am stronger than I was yesterday', true),
('strength', 'My resilience grows with each challenge I face', true),
('strength', 'I can handle whatever today brings', true),
('strength', 'I am a warrior, not a victim', true),
('strength', 'My strength comes from within, not from others'' approval', true),
('strength', 'I have overcome so much already', true),
('strength', 'I am building the life I deserve', true),
('strength', 'Every step forward is progress, no matter how small', true),
('strength', 'I choose courage over comfort', true),
('strength', 'I am reclaiming my power one day at a time', true),
('strength', 'I trust my ability to navigate difficult situations', true),
('strength', 'I am not broken, I am breaking free', true),
('strength', 'My voice matters and deserves to be heard', true),
('strength', 'I am writing a new chapter of my life', true),
('strength', 'I refuse to shrink myself to make others comfortable', true),
('strength', 'I am learning to stand in my truth', true),
('strength', 'My healing journey is my greatest act of rebellion', true),
('strength', 'I am becoming the person I needed when I was younger', true),
('strength', 'I choose progress over perfection', true),

-- Clarity affirmations (20 new)
('clarity', 'I see the situation clearly, without the fog of manipulation', true),
('clarity', 'My perception of reality is valid and trustworthy', true),
('clarity', 'I can distinguish between her words and her actions', true),
('clarity', 'I trust my gut feelings about people and situations', true),
('clarity', 'I see patterns clearly now that I couldn''t see before', true),
('clarity', 'I am no longer confused by gaslighting tactics', true),
('clarity', 'I can identify manipulation when I see it', true),
('clarity', 'My mind is clear and focused on my wellbeing', true),
('clarity', 'I see through the smoke and mirrors to the truth', true),
('clarity', 'I trust my memory and my experiences', true),
('clarity', 'I can separate her emotions from my own', true),
('clarity', 'I see her behavior for what it is, not what she says it is', true),
('clarity', 'I am learning to trust my own judgment', true),
('clarity', 'I can see the difference between love and control', true),
('clarity', 'I recognize healthy relationships from unhealthy ones', true),
('clarity', 'I see my worth clearly, regardless of her opinions', true),
('clarity', 'I understand that her problems are not mine to solve', true),
('clarity', 'I can see the forest through the trees', true),
('clarity', 'I am gaining clarity about what I want and need', true),
('clarity', 'I see my future clearly, and it is bright', true),

-- Peace affirmations (20 new)
('peace', 'I choose inner peace over external chaos', true),
('peace', 'My peace is more important than her approval', true),
('peace', 'I create calm in the storm of her emotions', true),
('peace', 'I am the eye of the hurricane - calm and centered', true),
('peace', 'I breathe in peace and breathe out tension', true),
('peace', 'I find serenity in accepting what I cannot change', true),
('peace', 'My peace is not dependent on her mood', true),
('peace', 'I cultivate tranquility in my heart and mind', true),
('peace', 'I choose stillness over reactivity', true),
('peace', 'I am learning to find peace in the present moment', true),
('peace', 'I create peaceful spaces wherever I go', true),
('peace', 'I release the need to control outcomes', true),
('peace', 'I find peace in my own company', true),
('peace', 'I am at peace with my decision to protect myself', true),
('peace', 'I choose harmony within myself', true),
('peace', 'I let go of what disturbs my peace', true),
('peace', 'I am learning to be comfortable with silence', true),
('peace', 'I find peace in my healing journey', true),
('peace', 'I create boundaries that protect my inner peace', true),
('peace', 'I am at peace with who I am becoming', true)

ON CONFLICT DO NOTHING;